config/routes.rb
require 'resque_web'
require 'resque/scheduler/server'
Vmscheduler::Application.routes.draw do
  devise_for :users
  resources :jobs, only: [:index, :show]

  resources :scheduled_actions

  resources :user_providers


  resources :actions


  resources :vms

  root to: 'dashboard#index'

  mount Resque::Server.new, at: "/resque"

end

app/models/user_provider.rb
class UserProvider < ActiveRecord::Base
  self.table_name = 'users_providers'

  belongs_to :user, class_name: 'User'
  belongs_to :provider, class_name: 'Provider'

  validates_presence_of :user, :provider, :api_key, :api_secret
end

app/controllers/user_providers_controller.rb
class UserProvidersController < ApplicationController
  before_action :set_user_provider, only: [:show, :edit, :update, :destroy]

  # GET /user_providers
  def index
    @user_providers = UserProvider.all
  end

  # GET /user_providers/1
  def show
  end

  # GET /user_providers/new
  def new
    @user_provider = UserProvider.new
  end

  # GET /user_providers/1/edit
  def edit
  end

  # POST /user_providers
  def create
    @user_provider = UserProvider.new(user_loaded_params)

    if @user_provider.save
      redirect_to @user_provider, notice: 'User provider was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /user_providers/1
  def update
    if @user_provider.update(user_loaded_params)
      redirect_to @user_provider, notice: 'User provider was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /user_providers/1
  def destroy
    @user_provider.destroy
    redirect_to user_providers_url, notice: 'User provider was successfully destroyed.'
  end

  private

  def user_loaded_params
    user_provider_params.merge(:user_id => current_user.id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user_provider
    @user_provider = UserProvider.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_provider_params
    params.require(:user_provider).permit(:provider_id, :api_key, :api_secret)
  end
end

app/helpers/user_providers_helper.rb
module UserProvidersHelper
end

app/views/user_providers/_form.html.erb
<%= simple_form_for(@user_provider) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :provider_id, collection: Provider.all %>
    <%= f.input :api_key %>
    <%= f.input :api_secret %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_providers/create.html.erb
<h1>UsersProviders#create</h1>
<p>Find me in app/views/users_providers/create.html.erb</p>

app/views/user_providers/edit.html.erb
<h1>Editing users_provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_provider %> |
<%= link_to 'Back', user_providers_path %>

app/views/user_providers/index.html.erb
<h1>Listing Providers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Api key</th>
      <th>Api secret</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_providers.each do |user_provider| %>
      <tr>
        <td><%= user_provider.user_id %></td>
        <td><%= user_provider.provider_id %></td>
        <td><%= user_provider.api_key %></td>
        <td><%= user_provider.api_secret %></td>
        <td><%= link_to 'Show', user_provider %></td>
        <td><%= link_to 'Edit', edit_user_provider_path(user_provider) %></td>
        <td><%= link_to 'Destroy', user_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users provider', new_user_provider_path %>

app/views/user_providers/new.html.erb
<h1>New users_provider</h1>

<%= render 'form' %>

<%= link_to 'Back', user_providers_path %>

app/views/user_providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_provider.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user_provider.provider_id %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @user_provider.api_key %>
</p>

<p>
  <strong>Api secret:</strong>
  <%= @user_provider.api_secret %>
</p>

<%= link_to 'Edit', edit_user_provider_path(@user_provider) %> |
<%= link_to 'Back', user_providers_path %>

app/views/user_providers/update.html.erb
<h1>UsersProviders#update</h1>
<p>Find me in app/views/users_providers/update.html.erb</p>