config/routes.rb
require 'resque_web'
require 'resque/scheduler/server'
Vmscheduler::Application.routes.draw do
  devise_for :users
  resources :jobs, only: [:index, :show]

  resources :scheduled_actions

  resources :user_providers


  resources :actions


  resources :vms

  root to: 'dashboard#index'

  mount Resque::Server.new, at: "/resque"

end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/_form.html.erb
<%= form_for(@action) do |f| %>
  <% if @action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action.errors.count, "error") %> prohibited this action from being saved:</h2>

      <ul>
      <% @action.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actions/edit.html.erb
<h1>Editing action</h1>

<%= render 'form' %>

<%= link_to 'Show', @action %> |
<%= link_to 'Back', actions_path %>

app/views/actions/index.html.erb
<h1>Listing actions</h1>

<table>
  <tr>
    <th>Scheduled Action</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actions.each do |action| %>
  <tr>
    <td><%= action.scheduled_action %></td>
    <td><%= link_to 'Show', action %></td>
    <td><%= link_to 'Edit', edit_action_path(action) %></td>
    <td><%= link_to 'Destroy', action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Action', new_action_path %>

app/views/actions/new.html.erb
<h1>New action</h1>

<%= render 'form' %>

<%= link_to 'Back', actions_path %>

app/views/actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @action.scheduled_action %>
</p>


<%= link_to 'Edit', edit_action_path(@action) %> |
<%= link_to 'Back', actions_path %>