config/routes.rb
require 'resque_web'
require 'resque/scheduler/server'
Vmscheduler::Application.routes.draw do
  devise_for :users
  resources :jobs, only: [:index, :show]

  resources :scheduled_actions

  resources :user_providers


  resources :actions


  resources :vms

  root to: 'dashboard#index'

  mount Resque::Server.new, at: "/resque"

end

app/views/tables/_jobs.html.erb
<%- model_class = Job -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:scheduled_action_id) %></th>
      <th><%= model_class.human_attribute_name(:cloudstack_job) %></th>
      <th><%= model_class.human_attribute_name(:action_result) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.scheduled_action, scheduled_action_path(job.scheduled_action) %></td>
        <td><%= job.cloudstack_job %></td>
        <td><%= job.action_result %></td>
        <td><%=l job.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tables/_scheduled_actions.html.erb
<%- model_class = ScheduledAction -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:vm_id) %></th>
      <th><%= model_class.human_attribute_name(:action) %></th>
      <th><%= model_class.human_attribute_name(:scheduled_time) %></th>
      <th><%= model_class.human_attribute_name(:frequency) %></th>
      <th><%= model_class.human_attribute_name(:recurring) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scheduled_actions.each do |scheduled_action| %>
      <tr>
        <td><%= scheduled_action.vm %></td>
        <td><%= scheduled_action.action %></td>
        <td><%= scheduled_action.scheduled_time %></td>
        <td><%= scheduled_action.frequency %></td>
        <td><%= scheduled_action.recurring %></td>
        <td><%=l scheduled_action.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scheduled_action_path(scheduled_action), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      scheduled_action_path(scheduled_action),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tables/_vms.html.erb
<%- model_class = Vm -%>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:api_key) %></th>
      <th><%= model_class.human_attribute_name(:api_secret) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vms.each do |vm| %>
      <tr>
        <td><%= vm.name %></td>
        <td><%= vm.uuid %></td>
        <td><%= vm.api_key %></td>
        <td><%= vm.api_secret %></td>
        <td><%= vm.provider.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vm_path(vm), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vm_path(vm),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>