config/routes.rb
require 'resque_web'
require 'resque/scheduler/server'
Vmscheduler::Application.routes.draw do
  devise_for :users
  resources :jobs, only: [:index, :show]

  resources :scheduled_actions

  resources :user_providers


  resources :actions


  resources :vms

  root to: 'dashboard#index'

  mount Resque::Server.new, at: "/resque"

end

app/helpers/layout_helper.rb
module LayoutHelper

  def link_class(path_list)
    Array.wrap(path_list).any? {|path| request.url.include?(path) } ? 'active' : nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Vmscheduler" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Cloudstack Scheduler", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Jobs", jobs_path, class: "active" %></li>
              <li><%= link_to "Schedule", scheduled_actions_path, class: "active" %></li>
              <li><%= link_to "Vms", vms_path, class: "active" %></li>
              <li><%= link_to "Providers", user_providers_path, class: "active" %></li>
              <% if current_user %>
                <li><%= link_to current_user.email, destroy_user_session_path %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <!-- may need this for devise if the above doesnt work
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
            -->
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>